[package]
name = "ssh-server"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
russh = "0.53.0"
russh-keys = "0.49.2"
tokio = { version = "1.40", features = ["full"] }  # 异步运行时
reqwest = { version = "0.12", features = ["json"] }  # HTTP 客户端
serde = { version = "1.0", features = ["derive"] }  # JSON 序列化
env_logger = "0.11"  # 日志实现
async-trait = "0.1.88"
rand_core = "0.6"

[dev-dependencies]
tokio = { version = "1.40", features = ["test-util"] }  # 测试
