[package]
name = "rust-sshd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
russh = "0.42"
russh-keys = "0.42"
russh-sftp = "2.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sha2 = "0.10"
base64 = "0.21"
dirs = "5.0"
clap = { version = "4.0", features = ["derive"] }
async-trait = "0.1"
futures = "0.3"
